version: 2

build:
  os: ubuntu-22.04

  tools:
    python: "3.12"

  jobs:
    post_create_environment:
      - pip install tox
      - tox -e docs --notest
      - .tox/docs/bin/pip freeze | grep -v '^cerulean' > docs/requirements.txt
    post_install:
      - pip install -r docs/requirements.txt
