version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/requirements.txt
    # install the package so that we have the dependencies and can import the files
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  builder: html
