# Run tests on push and pull request
name: continuous_integration
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          python3 -m pip install tox
          tox
