# Run tests on push and pull request
name: continuous_integration
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Run tests and upload coverage
        env:
          CODACY_PROJECT_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
        run: |
          cd $GITHUB_WORKSPACE
          python3 -c 'import platform ; print(platform.platform())'
          python3 -m pip install tox
          tox
          python-codacy-coverage -r coverage.xml
